BOARD_TAG = arduino_zero_native
ARCHITECTURE= samd
# Define ARM toolchain dir if not using Arduino supplied
ARM_TOOLS_DIR = $(HOME)/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1

# Define Arduino support package installation path where SAM device support has been installed
ARDUINO_PACKAGE_DIR := $(HOME)/.arduino15/packages

# include ../../Sam.mk
include /opt/arduino-mk/Sam.mk
